version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./phpBB3:/var/www/phpBB3
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
  php:
    image: php:7.2-fpm
    volumes:
      - ./phpBB3:/var/www/phpBB3
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example