version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - php
      - mysql
    volumes:
      - type: volume
        source: forum
        target: /var/www/forum
  php:
    image: php:7.2-fpm
    volumes:
      - type: volume
        source: forum
        target: /var/www/forum
        volume:
          nocopy: true
  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  forum: